CREATE TABLE IF NOT EXISTS 'user'(
    id INT PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    weight INT NOT NULL,
    height INT NOT NULL,
    img VARCHAR(255),
    PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS 'goal'(
    id INT PRIMARY KEY AUTOINCREMENT,
    user_id INT NOT NULL,
    goalType VARCHAR(255) NOT NULL,
    current INT NOT NULL,
    target INT,
    timeLimit INT,
    notes TEXT,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS 'group'(
    id INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    img VARCHAR(255),
    
)

CREATE TABLE IF NOT EXISTS 'groupGoal'(
    id INT PRIMARY KEYAUTOINCREMENT,
    group_id INT NOT NULL,
    goalType VARCHAR(255) NOT NULL,
    current INT NOT NULL,
    target INT,
    timeLimit INT,
    notes TEXT,
    
    FOREIGN KEY (group_id) REFERENCES group(id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE OR TABLE IF NOT EXISTS 'groupUser'(
    id INT PRIMARY KEY AUTOINCREMENT,
    group_id INT NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES group(id) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS 'diet'(

)
CREATE TABLE IF NOT EXISTS 'exercise'(

)
CREATE TABLE IF NOT EXISTS 'food'(
)

CREATE TABLE IF NOT EXISTS 'drink'(

)


