CREATE TABLE IF NOT EXISTS 'user'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL DEFAULT 'MALE',
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    weight INT NOT NULL,
    height INT NOT NULL,
    tweight INT NOT NULL,
    dob DATE NOT NULL,
    img VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS 'group'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS'goal'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT NOT NULL,
    groupID TEXT,
    goalType VARCHAR(255) NOT NULL,
    current INT NOT NULL,
    target INT,
    date DATE,
    notes TEXT,
    status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS 'group_user'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT NOT NULL,
    group_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (group_id) REFERENCES 'group'(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS 'food'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    calories INT NOT NULL,
    createdBy INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS 'drink'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    calories INT NOT NULL,
    createdBy INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS 'activity'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS 'exercise'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    distance INT NOT NULL,
    date DATE,
    type VARCHAR(255) NOT NULL,
    FOREIGN KEY (type) REFERENCES activity(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS 'meal'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    mealType VARCHAR(255) NOT NULL,
    date DATE,
    user_id INT NOT NULL,
    food TEXT,
    drink TEXT,
    FOREIGN KEY (food) REFERENCES food(name) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (drink) REFERENCES drink(name) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);


