CREATE TABLE IF NOT EXISTS 'user'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    weight INT NOT NULL,
    height INT NOT NULL,
    img VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS 'goal'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT NOT NULL,
    goalType VARCHAR(255) NOT NULL,
    current INT NOT NULL,
    target INT,
    timeLimit INT,
    notes TEXT,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);
